apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app_name}
  namespace: ${app_name}
  labels:
    app: ${app_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${app_name}
  template:
    metadata:
      labels:
        app: ${app_name}
    spec:
      containers:
      - name: ${app_name}
        image: ghost
        env:
        - name: url
          value: https://ade-kaas-demo.westeurope.cloudapp.azure.com/${app_name}
        - name: NODE_ENV
          value: development
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
        ports:
        - name: http
          containerPort: 2368
          protocol: TCP
      restartPolicy: Always