apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ${app_name}
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/${app_name}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client