apiVersion: v1
kind: Service
metadata:
  name: ${app_name}
  namespace: ${app_name}
spec:
  type: ClusterIP
  selector:
    app: ${app_name}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368