name: ADE demo
on: [workflow_dispatch]

jobs:
  deploy-environment:
    runs-on: ubuntu-latest
    steps:

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Add Azure CLI DevCenter extension
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az extension add --source https://fidalgosetup.blob.core.windows.net/cli-extensions/devcenter-0.1.0-py3-none-any.whl --yes

    - name: Azure Deployment Environment(ADE) - Create environment
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          # $params = "{ 'name': 'firstMsi', 'location': 'northeurope' }"
          az devcenter dev environment create `
            --dev-center-name dc-devx `
            --project-name the-phoenix-project `
            --environment-name my-cicd-environment `
            --environment-type sandbox `
            --catalog-item-name FunctionApp `
            --catalog-name  CommunityTemplates `
            # --parameters $params
