name: ADE demo
on: [workflow_dispatch]

jobs:
  deploy-environment:
    runs-on: ubuntu-latest
    steps:

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Deployment Environment(ADE) - Create environment
      uses: azure/CLI@v1
      with:
        azcliversion: 2.45.0
        inlineScript: |
          az extension add --name devcenter --yes
          az devcenter dev environment create --dev-center-name dc-devx --project-name the-phoenix-project --environment-name my-cicd-environment --environment-type sandbox --catalog-item-name FunctionApp --catalog-name  CommunityTemplates

  build-and-deploy-webapp:
    needs: [deploy-environment]
    runs-on: ubuntu-latest
    steps:

    - name: deploy web app
      run: echo "deploy web app"

    # wait 10 seconds
    - name: Wait 10 minutes
      uses: jakejarvis/wait-action@master
      with:
        time: '5m'

  build-and-deploy-api:
    needs: [deploy-environment]
    runs-on: ubuntu-latest
    steps:

    - name: deploy web api
      run: echo "deploy web api"

  load-testing:
    needs: [build-and-deploy-webapp, build-and-deploy-api]
    runs-on: ubuntu-latest
    steps:

    - name: init
      run: echo "init"
    
    - name: load test
      run: echo "load test"
    
    - name: publish results
      run: echo "push results"

  delete-environment:
    needs: [load-testing]
    runs-on: ubuntu-latest
    steps:

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Deployment Environment(ADE) - Delete environment
      uses: azure/CLI@v1
      with:
        azcliversion: 2.45.0
        inlineScript: |
          az extension add --name devcenter --yes
          az devcenter dev environment delete --dev-center-name dc-devx --project-name the-phoenix-project --name my-cicd-environment --yes
