name: demo
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy environment
        uses: azure/cli@v1
        with:
          azcliversion: 2.45.0
          inlineScript: |
            az extension add --name devcenter --yes
            az devcenter dev environment create \
                --dev-center-name dc-devx \
                --project-name the-phoenix-project \
                --environment-name demo-environment \
                --environment-type sandbox \
                --catalog-item-name WebApp \
                --catalog-name  CommunityTemplates
